services:
    scraper-api:
      container_name: scraper-api
      # Crea la imagen con el archivo Dockerfile de esta misma carpeta
      image: scraper:prd
      build: .
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8090:8090"
      env_file:
        - ../envs/file_scraper.env
      networks:
        - db-net
      # command: tail -f /home/jonnattan/requirements.txt
networks:
  db-net:
