services:
    scraper-api:
      container_name: scraper-api
      image: jonnattangc/scraperservice:1.0.0
      restart: none
      #volumes:
      #  - ./app:/home/jonnattan/app
      ports:
        - "8090:8090"
      env_file:
        - ../envs/file_scraper.env
      networks:
        - db-net
      # command: tail -f /home/jonnattan/requirements.txt
networks:
  db-net:
