version: '3.9'
services:
    scraper-dev:
      container_name: scraper-dev
      image: scraper:dev
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8091:8091"
      env_file:
        - ../file_scraper.env
      networks:
        - net
      command: tail -f /home/jonnattan/requirements.txt

networks:
  net:
