version: "3.9"
services:
    scraper-api:
      container_name: scraper-api
      # Crea la imagen con el archivo Dockerfile de esta misma carpeta
      image: scraper-img:1.0
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8090:8090"
      env_file:
        - ../file_scraper.env
      networks:
        - db-net
networks:
  db-net:
